// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qadqcbhxldfrzbkxbrnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZHFjYmh4bGRmcnpia3hicm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMDE2ODEsImV4cCI6MjA0OTY3NzY4MX0.9becz3aW2h-3setwpeSajSL7xXRSxQBohAzaSAVznYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);